// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjeTia4-4xYOUxoFB4phya8IY7rilgAQU',
    appId: '1:715631995986:web:544bb787c064d72fc6038b',
    messagingSenderId: '715631995986',
    projectId: 'questify-e8f5e',
    authDomain: 'questify-e8f5e.firebaseapp.com',
    storageBucket: 'questify-e8f5e.firebasestorage.app',
    measurementId: 'G-ZZSN51HX3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyKdLQXy3lHLJvPCTjH74E0lRZaSdCLc',
    appId: '1:715631995986:android:78e5340b9430bb93c6038b',
    messagingSenderId: '715631995986',
    projectId: 'questify-e8f5e',
    storageBucket: 'questify-e8f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7S_9O1vEXwW8ed-9tFS1VMZrJ3zIFyJo',
    appId: '1:715631995986:ios:9286f07ad9c09435c6038b',
    messagingSenderId: '715631995986',
    projectId: 'questify-e8f5e',
    storageBucket: 'questify-e8f5e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7S_9O1vEXwW8ed-9tFS1VMZrJ3zIFyJo',
    appId: '1:715631995986:ios:9286f07ad9c09435c6038b',
    messagingSenderId: '715631995986',
    projectId: 'questify-e8f5e',
    storageBucket: 'questify-e8f5e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjeTia4-4xYOUxoFB4phya8IY7rilgAQU',
    appId: '1:715631995986:web:9390a92a16fd7bdbc6038b',
    messagingSenderId: '715631995986',
    projectId: 'questify-e8f5e',
    authDomain: 'questify-e8f5e.firebaseapp.com',
    storageBucket: 'questify-e8f5e.firebasestorage.app',
    measurementId: 'G-DJZG0Y1LXG',
  );
}
